#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: api-test-nodejs
  type: web
  plan: free
  runtime: node
  region: oregon
  buildCommand: corepack enable && corepack prepare yarn@stable --activate && yarn && yarn rw build api
  startCommand: yarn start
  envVars:
  - key: NODE_VERSION
    value: 18
  - key: DATABASE_URL
    fromDatabase:
      name: list-db
      property: connectionString

# - name: list-web
#   type: web
#   env: static
#   buildCommand: yarn install && yarn rw deploy render web
#   staticPublishPath: ./web/dist
#   envVars:
#   - key: NODE_VERSION
#     value: 18
#   - key: SKIP_INSTALL_DEPS
#     value: true
#   routes:
#   - type: rewrite
#     source: /.redwood/functions/*
# #####
# # NOTE: replace destination api url after first deploy to Render
# # example:
# #   destination: https://myredwoodproject-api.onrender.com/*
# #####
#     destination: replace_with_api_url/*
#   - type: rewrite
#     source: /*
#     destination: /200.html

# - name: list-api
#   type: web
#   plan: free
#   env: node
#   region: oregon
#   buildCommand: yarn && yarn rw build api
#   startCommand: yarn rw deploy render api
#   envVars:
#   - key: NODE_VERSION
#     value: 18
#   - key: DATABASE_URL
#     fromDatabase:
#       name: list-db
#       property: connectionString

# databases:
#   - name: list-db
#     region: oregon